### ISSUE TITLE
Error with install.sh

### ISSUE THREAD

**Issue by ABellesis** [atbogetti/wess#2]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/agb53/BdpA/WSH_2045_sim/Unfolding/Helix1_Helix2/Analyzing_2D_config/WestpaTools/setup.py'"'"'; __file__='"'"'/home/agb53/BdpA/WSH_2045_sim/Unfolding/Helix1_Helix2/Analyzing_2D_config/WestpaTools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/agb53/BdpA/WSH_2045_sim/Unfolding/Helix1_Helix2/Analyzing_2D_config/WestpaTools/
    Complete output (29 lines):
    running develop
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-21278.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.6/dist-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.readthedocs.io/en/latest/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/agb53/BdpA/WSH_2045_sim/Unfolding/Helix1_Helix2/Analyzing_2D_config/WestpaTools/setup.py'"'"'; __file__='"'"'/home/agb53/BdpA/WSH_2045_sim/Unfolding/Helix1_Helix2/Analyzing_2D_config/WestpaTools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by AnthonyBogetti** [comment]
This might work for future instances of this issue:

python -m pip install -e .
